sonar.organization=kube-pod404
sonar.projectKey=KUBE-POD404_opslora-lora-ai-service
sonar.projectName=opslora-lora-ai-service
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
